#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python TDNet.py --source /root/capsule/data/Leeds.mp4 --save ../results --end 100
